server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
